const countryName = [
    'United Arab Emirates',
    'Argentina',
    'Austria',
    'Australia',
    'Belgium',
    'Bulgaria',
    'Brazil',
    'Canada',
    'Switzerland',
    'China',
    'Colombia',
    'Cuba',
    'Czech Republic',
    'Germany',
    'Egypt',
    'France',
    'United Kingdom',
    'Greece',
    'Hong Kong',
    'Hungary',
    'Indonesia',
    'Ireland',
    'Israel',
    'India',
    'Italy',
    'Japan',
    'South Korea',
    'Lithuania',
    'Latvia',
    'Morocco',
    'Mexico',
    'Malaysia',
    'Nigeria',
    'Netherlands',
    'Norway',
    'New Zealand',
    'Philippines',
    'Poland',
    'Portugal',
    'Romania',
    'Serbia',
    'Russia',
    'Saudi Arabia',
    'Sweden',
    'Singapore',
    'Slovenia',
    'Slovakia',
    'Thailand',
    'Turkey',
    'Taiwan',
    'Ukraine',
    'United States',
    'Venezuela',
    'South Africa',
]

export default countryName;